config/routes.rb
Rails.application.routes.draw do
  
  resources :recipes, :categories

  get '/admin', to: 'admin#admin', as: 'admin'
  get '/contact', to: 'home#contact', as: 'contact'
  get '/about', to: 'home#about', as: 'about'
  root to: 'home#index'

  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :category
  validates_presence_of :title, :ingredients, :instructions, :category
  
  def self.find_all_by_query(query)
    query = query.downcase
    query = "%#{query}%"
#    categoryQuery = categoryQuery.downcase
#    categoryQuery = "%#{categoryQuery}%"
    
    Recipe.where(['lower(title) like ?
                  OR lower(ingredients) like ?
                  OR lower(instructions) like ?',
                  query, query, query])
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_secure_password
    
  def self.authenticate(username, password)
    user = User.where(username: username).first
    user && user.authenticate(password)
  end  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

  def show
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate, :except => [:index, :show]
  before_action :set_title
  
  private
  
  def authenticate
    if user = authenticate_with_http_basic {|user, password| User.authenticate(user, password)}
      session[:user_id] = user.id
      session[:logged_in] = true
    else
      request_http_basic_authentication
    end
  end
  
  helper_method :logged_in?
  helper_method :current_user

  def logged_in?
    session[:logged_in]
  end
  
  def set_title    
    @title = "Cookbook"   
  end
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @category = Category.new
    @categories = Category.all.collect{|c| [c.name, c.id] }
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
  
    def get_categories
      @categories = Category.all.collect{|c| [c.name, c.id] }
    end
    
    def get_recipes
      @recipes = Recipes.all.collect{|c| [c.name, c.id] }
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @number_of_recipes = Recipe.count
  end

  def about
  end
  
  def contact
    @coles_age = Date.today.year - 1994
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :get_categories, :only =>[:new, :edit, :create, :update]
  before_action :authenticate, :except => [:index, :show]
  
  # GET /recipes
  # GET /recipes.json
  def index
#    if params[:q] && params[:d]
#      @recipes = Recipe.find_all_by_query(params[:q], params[:d])
    if params[:q]
      @recipes = Recipe.find_all_by_query(params[:q])
    else
      @recipes = Recipe.all
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @categories = Category.all.collect{|c| [c.name, c.id] }
  end

  # GET /recipes/1/edit
  def edit
    @categories = Category.all.collect{|c| [c.name, c.id] }
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.includes(:category).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :ingredients, :instructions, :calories, :category_id)
    end
  
    def get_categories
      @categories = Category.all.collect{|c| [c.name, c.id] }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/admin/admin.html.erb
<h2>Login Status</h2>
<p>Welcome to the Greatest Cookbook in the World, because it is on the internet.</p>
<p><% if logged_in? %>
    You are logged in as <%= current_user.username %>
   <% end %>
</p>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', category_path %>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>

<table>
  <tr>
    <th>Category</th>
    <th colspan="2">&nbsp;</th>
  </tr>
  
  <% @categories.each do |category| %>
  <tr>
    <td><%= link_to category.name, category %></td>
    
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><% if logged_in? %><%= button_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %><% end %></td>
  </tr>
  <% end %>
</table>

<% if logged_in? %>
  <%= link_to 'New category', new_category_path %>
<% end %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<article>
  <header>
    <h2>
      <%= @category.name %>
      [ <%= link_to 'Edit', edit_category_path(@category) %> ]
    </h2>
  </header>

  <h3>Recipes: </h3>
  <% @category.recipes.each do |recipe| %>
    <p><%= recipe.title %></p>
  <% end %>

<p><%= link_to 'Back', categories_path %></p>

app/views/home/about.html.erb
<h2>About</h2>
<p>This is a simple cookbook application I wrote. I hope you like it.</p>

app/views/home/contact.html.erb
<h2>Contact</h2>
<p>Name: Cole Kulig</p>
<p>Age: <%= @coles_age %></p>
<p>Hobbies: Video Games, Watching TV, coding, and looking up Computer Hardware and Car parts</p>
<p>Graduation Date: December 2017</p>

app/views/home/index.html.erb
<%= render "/shared/search" %>
<h2>Latest Recipes</h2>
<p>There are <%= @number_of_recipes %> recipes total.</p>
<p><% if logged_in? %>
    <%= link_to 'New recipe', new_recipe_path %>
   <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
   <head>
     <title><%= @title %></title>
     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
     <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
     <%= csrf_meta_tags %>
   </head>
   <body>
     <div class="container">
       <header>
        <h1>Our Cookbook</h1>
       </header>
       <section class="content">
        <nav>
         <%=link_to_unless_current 'Home', root_url %>
         <%=link_to_unless_current 'Recipes', recipes_url %>
         <%=link_to_unless_current 'Categories', categories_url %>
         <%=link_to_unless_current 'About', about_url %>
         <%=link_to_unless_current 'Contact', contact_url %>
        </nav>
        <% if notice %>
          <div id="notice">
            <%= notice %>
          </div>
        <% end %>
        <%= yield %>
       </section>
       <footer>
        <h4>Copyright <%=Date.today.year %> OurCookbook</h4>
       </footer>
     </div>
   </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.select :category_id, @categories, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </div>
  <div class="field">
    <%= f.label :calories %><br>
    <%= f.text_area :calories %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<%= render "/shared/search" %>
<h1>Listing recipes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Category</th>
    <th>Last Updated</th>
    <th colspan="2">&nbsp;</th>
  </tr>
  
  <% @recipes.each do |recipe| %>
  <tr>
    <td><%= link_to recipe.title, recipe %></td>
    <td><%= recipe.category.name rescue "No category" %></td>
    <td><%= time_ago_in_words(recipe.updated_at) %> ago</td>
    <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
    <td><% if logged_in? %><%= button_to 'Destroy', recipe, confirm: 'Are you sure?', method: :delete %><% end %></td>
  </tr>
  <% end %>
</table>

<% if logged_in? %>
  <%= link_to 'New recipe', new_recipe_path %>
<% end %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<article>
  <header>
    <h2>
      <%= @recipe.title %>
      [ <%= link_to 'Edit', edit_recipe_path(@recipe) %> ]
    </h2>
  </header>

  <p>Category: <%= h(@recipe.category.name) rescue 'No category found' %></p>
  
  <h3>Calories:</h3>
  <p><%= @recipe.calories %></p>
  
  <h3>Ingredients:</h3>
  <p><%= @recipe.ingredients %></p>

  <h3>Instructions</h3>
  <p><%= @recipe.instructions %></p>
</article>

<p><%= link_to 'Back', recipes_path %></p>

app/views/shared/_search.html.erb
<%= form_tag recipes_url, method: :get do %>
  <label for="query">Keywords: </label>
  <input type="search" id="query" name="q" value="<%= params[:q] %>">
  <input type="dropdown" id="query" name="d" value="<%= params[:d] %>">
  <input type="submit" value="Search">
<% end %>